export const BRAND = {
  name: 'Orange Data Tech',
  tagline: 'Cyber Security Solutions',
  logo: '/orange-data-tech-logo.png',
  logoUrl: 'https://orangedatatech.com/wp-content/uploads/2026/05/OrangeDataTech_Logo2.png',
  email: 'info@orangedatatech.com',
  phone: '+1 840 841 25 69',
  addresses: [
    { label: 'UK Office', value: '120 Bishopsgate, London, EC2N 4AD, United Kingdom' },
    { label: 'India Office', value: 'Cyber Towers, HITEC City, Madhapur, Hyderabad, Telangana 500081, India' },
  ],
  address: '120 Bishopsgate, London, EC2N 4AD, United Kingdom',
  colors: {
    // Fort template base (pixel-matched)
    dark: '#06021D',
    darkCard: '#0D0828',
    purple: '#F47920',
    purpleDark: '#D96A10',
    purpleLight: '#FF9A4D',
    light: '#EEF6FC',
    lightAlt: '#F4FAFF',
    white: '#FFFFFF',
    textMuted: '#8B8FA3',
    // Orange Data Tech accent overlay on buttons/highlights
    orange: '#F47920',
    orangeDark: '#D96A10',
  },
  images: {
    heroBg: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-63.jpg',
    heroVisual: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-73.jpg',
    trust: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-71.jpg',
    earth: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-72.jpg',
    contactEarth: 'https://fort.themerex.net/wp-content/uploads/2025/12/custom-img-03.jpg',
    team: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-70.jpg',
    blog1: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-77.jpg',
    blog2: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-80.jpg',
    blog3: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-71.jpg',
    blogBg: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-94.jpg',
    aboutBg: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-63.jpg',
    aboutHero: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-67.jpg',
    aboutExpertise: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-64.jpg',
    aboutSolutions: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-68.jpg',
    aboutBlog1: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-75.jpg',
    aboutBlog2: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-76.jpg',
    aboutBlog3: 'https://fort.themerex.net/wp-content/uploads/2026/01/custom-img-77.jpg',
  },
} as const;
